//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeredoTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeredoTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cmd.exe.
        /// </summary>
        internal static string CMD_START {
            get {
                return ResourceManager.GetString("CMD_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ipconfig.
        /// </summary>
        internal static string COMMAND_IPCONFIG {
            get {
                return ResourceManager.GetString("COMMAND_IPCONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sc config iphlpsvc start= auto.
        /// </summary>
        internal static string IPHELPER_SET_AUTO {
            get {
                return ResourceManager.GetString("IPHELPER_SET_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a net start iphlpsvc.
        /// </summary>
        internal static string IPHELPER_START {
            get {
                return ResourceManager.GetString("IPHELPER_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a net stop iphlpsvc.
        /// </summary>
        internal static string IPHELPER_STOP {
            get {
                return ResourceManager.GetString("IPHELPER_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C:\Windows\System32\drivers\etc\hosts.
        /// </summary>
        internal static string PATH_HOSTS {
            get {
                return ResourceManager.GetString("PATH_HOSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable-NetAdapterBinding -Name &quot;*&quot; -ComponentID ms_tcpip6.
        /// </summary>
        internal static string POWERSHELL_ENABLE_IPV6_ALL_INTERFACES {
            get {
                return ResourceManager.GetString("POWERSHELL_ENABLE_IPV6_ALL_INTERFACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a powershell.exe.
        /// </summary>
        internal static string POWERSHELL_START {
            get {
                return ResourceManager.GetString("POWERSHELL_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sc query &quot;iphlpsvc&quot; | find &quot;RUNNING&quot;.
        /// </summary>
        internal static string SERVICE_IPHELPER_STATUS {
            get {
                return ResourceManager.GetString("SERVICE_IPHELPER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a netsh interface Teredo set state disable.
        /// </summary>
        internal static string TEREDO_DISABLE {
            get {
                return ResourceManager.GetString("TEREDO_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a netsh interface Teredo set state servername=default.
        /// </summary>
        internal static string TEREDO_STATE_SERVERNAME_RESET {
            get {
                return ResourceManager.GetString("TEREDO_STATE_SERVERNAME_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a netsh interface teredo show state.
        /// </summary>
        internal static string TEREDO_STATE_SHOW {
            get {
                return ResourceManager.GetString("TEREDO_STATE_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a netsh interface teredo set state type=default.
        /// </summary>
        internal static string TEREDO_STATE_TYPE_RESET {
            get {
                return ResourceManager.GetString("TEREDO_STATE_TYPE_RESET", resourceCulture);
            }
        }
    }
}
